### ISSUE TITLE
Add 'Book' and 'View Profile' buttons on worker well in search result

### ISSUE THREAD

**Issue by fargobie** [aptus-dev/jobcenter-angularfire#3]
Add 'Book' and 'View Profile' buttons on worker well in search result

Client wants to have two buttons:
1. Book - immediately book (call up modal and submit form)
2. View Profile - opens profile page

@audiae prepare the buttons and I'll add the book functions

**Comment by audiae** [comment]
Buttonnya udah dimasukkin tapi modalnya tak bisa kluar

**Comment by fargobie** [comment]
belom ada functionnya, nanti gue tambahin

**Comment by fargobie** [comment]
done
